trigger:
  branches:
    include:
    - master
    - develop
    - feature*
    - hotfix*
    - bug*
    - release*
   
pool:
  vmImage: 'ubuntu-latest'

variables:
  group: coveralls orc-shared
  BUILD_REACT: true

steps:
- task: NodeTool@0
  displayName: 'Use Node 12.x'
  inputs:
    versionSpec: 12.x


# - task: PowerShell@1
#   displayName: 'Build BetterRetail'
#   inputs:
#     scriptType: 'inlineScript'
#     inlineScript: |
#       # You can write your powershell scripts inline here. 
#       # You can also pass predefined and custom variables to this scripts using arguments
      
#       gci env:
      
#         Write-Host "Hello World"
#   continueOnError: true

    
  
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: true

- task: Npm@1
  displayName: 'npm prune'
  inputs:
    command: 'custom'
    customCommand: 'prune'

- task: Npm@1
  displayName: 'npm ls --depth=1'
  continueOnError: true
  inputs:
    command: 'custom'
    customCommand: 'ls --depth=1'

- task: Npm@1
  displayName: 'npm run lint'
  inputs:
    command: 'custom'
    customCommand: 'run lint'

- task: Npm@1
  displayName: 'npm run coverage'
  inputs:
    command: 'custom'
    customCommand: 'run coverage'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'printenv'
  env:
    CI_NAME: 'Azure DevOps orc-shared'
    CI_BUILD_NUMBER: $(Build.BuildNumber)
    CI_BUILD_URL: $(Build.Repository.Uri)
    CI_BRANCH: $(Build.SourceBranch)
    COVERALLS_REPO_TOKEN: $(CoverallsToken)
    CI_PULL_REQUEST: $(System.PullRequest.PullRequestId)


- task: Npm@1
  displayName: 'npm run coveralls'
  inputs:
    command: 'custom'
    customCommand: 'run coveralls'
  env:
    CI_NAME: 'Azure DevOps orc-shared'
    CI_BUILD_NUMBER: $(Build.BuildNumber)
    CI_BUILD_URL: $(Build.Repository.Uri)
    CI_BRANCH: $(Build.SourceBranch)
    COVERALLS_REPO_TOKEN: $(CoverallsToken)
    CI_PULL_REQUEST: $(System.PullRequest.PullRequestId)

  # - script: |
  #     pip install coveralls
  #     export CIRCLE_BRANCH=$BUILD_SOURCEBRANCH
  #     coveralls
  #   displayName: 'coveralls'
  #   env:
  #     CIRCLECI: 1
  #     CIRCLE_BUILD_NUM: $(Build.BuildNumber)
  #     COVERALLS_REPO_TOKEN: $(CoverallsToken)