language: node_js
node_js:
  - "10"
  - "12"
cache:
  directories:
    - "node_modules"
env:
  - BUILD_REACT=true
script: "npm run coverage"
after_success: "npm run coveralls"
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-fr
