os: linux
language: node_js
node_js:
  - "10"
  - "12"
env:
  global:
    - BUILD_REACT=true
script:
  - npm run lint
  - npm run coverage
after_success: npm run coveralls
before_deploy: export NPM_TAG=`node_modules/.bin/orc-scripts getDist`
deploy:
  provider: npm
  edge: true
  email: joclefrancois@gmail.com
  api_token:
    secure: izZ59PXWZlmze9YemSK8OZ+fJK1GQ79s3D3Jwp8Y1WoGZicUgRC4HczY+eZuLd5iAYa6+GqyS6mXE3x3wuCCgalaDHkjEK32o+Akkhi9qc9NAUjUPw9I5EwAeu+8N/tZIiCTW5ljHwsq5F6t4Z+WbKEa3HolZg7hm3RaZPdDLPISVzCFwINgQ9c5lMiT4o1fX+2oNgF1HDTRgREn9eI1tsFwCnh3i0fWw+9VRszNFlGA2+v9oXnCySFRSXPWFI+19qZKRXP4SINIBGvWX9nMedhlur7cpj8c2eryINMgNnUeapBgXlx73afUL0UsHrcS81jsdmn/seFX7rzF6d1ndhTiF41Xd5vtVAymPNrDRlymFrkm8tqbfzXQYg1Z7I/JAgsdzjgg6VHG2l4RwL/BxKxt13bSv7n9YuWsEiTEgDodQk4FmMW82FWPOYGWfq273bID1nKVnPvMTJPa6xeYeSxjhsn5OMkibOTA/FZyu+3MltIvLyzKNnIIosHNC52BFsH6sYyhzxGuW/pcdfIRit2RQIri5OtZES78R2kkXN2GQ3iQ/8neZ+2cW29Jo3aJRz0ZjOnkTtSY7l8KRSbmcV3leKSHuj4D1rQARDxfb6oF3cMO844FU/7u2SNFr1uC+6bYZiVLdb/Hymuruno/p7bVukeld5D8qjIDLfu2I9M=
  tag: "$NPM_TAG"
  on:
    repo: Orckestra/orc-shared
    tags: true
    condition: "$TRAVIS_NODE_VERSION = 12"
