import { makeActionTypes } from "./makeApiAction";

export const GET_AUTHENTICATION_PROFILE = "GET_AUTHENTICATION_PROFILE";

export const [
	GET_AUTHENTICATION_PROFILE_REQUEST,
	GET_AUTHENTICATION_PROFILE_SUCCESS,
	GET_AUTHENTICATION_PROFILE_FAILURE,
] = makeActionTypes(GET_AUTHENTICATION_PROFILE);

export const SIGN_OUT = "SIGN_OUT";

export const [
	SIGN_OUT_REQUEST,
	SIGN_OUT_SUCCESS,
	SIGN_OUT_FAILURE,
] = makeActionTypes(SIGN_OUT);
